- hosts: Dev
  become: true
  tasks:
    - name: Installing openjdk on Debian
      apt: name=openjdk-11-jdk state=present update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Installing openjdk on RedHat
      yum: name=java-1.8.0-openjdk state=present update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: Creating apps directory
      file:
        path: /opt/apps
        state: directory
        mode: '0755'

    - name: Downloading Maven 3.8.1
      get_url:
        url: https://downloads.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
        dest: /opt/apps/maven381.tgz

    - name: Extracting the package
      unarchive:
        src: /opt/apps/maven381.tgz
        dest: /opt/apps/
        mode: '0755'
        remote_src: yes